### ISSUE TITLE
Menu de criação de jogo

### ISSUE THREAD

**Issue by JoaoFelipe** [GRUPO-ES2-GJLRT/XADREZ_ES2#2]
Menu que permita, antes do início do jogo, definir tempo de jogo/tempo de jogada/sem tempo.

Não sei muito bem como que joga com tempo. Alguém tem ideia de quais opções tem que ter?

**Comment by lvieirajr** [comment]
3 modos de relógio serão implementados na interface, como 3 modos de jogo.

**Comment by lvieirajr** [comment]
Esforço estimado: 3

**Comment by robertosampaio** [comment]
Procurei no jogo que tenho aqui de xadrez (Chessmaster Grandmaster Edition) e ele possui 4 modos de relógio. Podemos escolher os 3 primeiros.

Minutes per Game - Quantidade fixa de minutos para o jogo inteiro.
Moves per Minutes - Quantidade fixa de minutos por quantidade de jogadas (p. ex.: 40 minutos por 40 jogadas)
Fischer Time - Começa com um tempo fixo e a cada jogada você ganha mais um tempo. Ex: 5min fixos e 3 segundos de bonus por jogada.
Hourglass - Parece com o primeiro, mas é mais hardcore, tipo 30 segundos o jogo todo.
