### ISSUE TITLE
Tela de jogo (tabuleiro)

### ISSUE THREAD

**Issue by JoaoFelipe** [GRUPO-ES2-GJLRT/XADREZ_ES2#3]
Mostrar tabuleiro com peças, tempos

**Comment by lvieirajr** [comment]
Esforço estimado: 5

**Comment by JoaoFelipe** [comment]
Fiz o construtor do tabuleiro colocar as peças. Acho que isso pode facilitar na parte gráfica
Não pretendo fazer a parte gráfica dessa issue

A posição pode ser acessada por (x, y).
(0, 0) é equivalente a A1 no xadrez e (6, 7) é equivalente a G8. 
Ou seja a rainha branca fica em (3, 0) e a preta em (3, 7)
