### ISSUE TITLE
Modelagem inicial

### ISSUE THREAD

**Issue by JoaoFelipe** [GRUPO-ES2-GJLRT/XADREZ_ES2#4]
Fazer uma modelagem inicial de como vai ficar o sistema.

Acho válido fazer algo inicialmente que considere game loop, tabuleiro e peças, cada peça sabendo para onde pode ir, de acordo com a posição no tabuleiro e com a sua cor

A parte de IA, minmax pode ficar pra depois, mas se quiserem fazer junto, tudo bem

**Comment by lvieirajr** [comment]
Esforço estimado: 5
